# Generated by Django 3.2.1 on 2024-08-20 19:18

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('discount_percentages', models.DecimalField(decimal_places=0, max_digits=3)),
                ('estimated_setup_time_by_user', models.CharField(default='10 minut', max_length=50)),
                ('estimated_setup_time_by_system', models.CharField(default='<1 minuta', max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('support', models.BooleanField(default=False)),
                ('customizable', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('show_on_landing_page', models.BooleanField(default=False)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.create_product_image_path)),
                ('alt', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('discount_percentages', models.DecimalField(decimal_places=0, max_digits=3)),
                ('estimated_setup_time_by_user', models.CharField(default='10 minut', max_length=50)),
                ('estimated_setup_time_by_system', models.CharField(default='<1 minuta', max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('support', models.BooleanField(default=False)),
                ('customizable', models.BooleanField(default=True)),
                ('main_rgb_color', models.CharField(default='#FFFFFF', max_length=10)),
                ('secondary_rgb_color', models.CharField(default='#FFFFFF', max_length=10)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True)),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['price'],
            },
        ),
    ]
