# Generated by Django 3.2.1 on 2024-08-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240824_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='featues',
            field=models.ManyToManyField(null=True, to='products.Feature'),
        ),
        migrations.AddField(
            model_name='product',
            name='featues',
            field=models.ManyToManyField(null=True, to='products.Feature'),
        ),
    ]
